### PR TITLE
First draft of new Memento design

### PR DESCRIPTION
**Pull request by ajs6f**
https://github.com/trellis-ldp/trellis-cassandra/issues/60

### CODE REVIEW

**Comment by ajs6f** [comment]
@gregjan Any problem with me merging this? If it turns out to cause any problems I would be astonished, but I can revert if needed, of course.

**Comment by gregjan** [comment]
Please rebase on master after merging the docker PR.. That will help with this and any future testing involving schema change.

**Comment by ajs6f** [comment]
Ah, I didn't see that you had gotten it to pass Travis. I'll go over there and merge.

**Comment by gregjan** [comment]
Oh wait, it's in master already.  Okay I was looking for a branch, but will test master.

**Pull request merged**
